### ISSUE TITLE
Pen tool

### ISSUE THREAD

**Issue by F-star** [F-star/suika#124]
- [x] draw path tool  #126 
- [ ] anchor / control select tool
  - [x] support move anchor #127
  - [x] support move handleIn and handleOn
- [x] close path #128
- [x] double click to active path editor #130
- [x] select box #131
