### ISSUE TITLE
0.1.0 RoadMap

### ISSUE THREAD

**Issue by F-star** [F-star/suika#209]
- [ ] Support setting background color
- [x] #211
- [ ] Design and use project logo
- [x] #213
- [ ] Support blend modes for graphics
- [ ] Support fullscreen mode
- [ ] Property panel optimization - use dedicated icons for properties
- [ ] Support up/down arrow keys or drag to modify property values in input fields
- [ ] optimize pen tool

**Comment by F-star** [comment]
中文

- [ ] 支持设置背景色
- [x] paint 控件优化（支持直接设置透明度、设置是否可见）
- [ ] 设计并使用项目 logo
- [ ] 新创建图形使用正确的名字 + 数字，如 group 5
- [ ] 图形支持混合模式
- [ ] 支持全屏模式
- [ ] 属性面板优化 - 属性使用专有 icon
- [ ] 属性值输入框支持上下方向键或拖拽修改属性值
